Document: gpu-viv-bin
Title: Debian gpu-viv-bin Manual
Author: <insert document author here>
Abstract: This manual describes what gpu-viv-bin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gpu-viv-bin/gpu-viv-bin.sgml.gz

Format: postscript
Files: /usr/share/doc/gpu-viv-bin/gpu-viv-bin.ps.gz

Format: text
Files: /usr/share/doc/gpu-viv-bin/gpu-viv-bin.text.gz

Format: HTML
Index: /usr/share/doc/gpu-viv-bin/html/index.html
Files: /usr/share/doc/gpu-viv-bin/html/*.html
