#!/bin/sh

if [ "x$1" = "xremove" ]; then
	# imx-gpu-viv-* should still be configured.
	# Because link groups can not be changed once created,
	# the original link group has to be recreated here :(
	update-alternatives \
		--install /usr/lib/galcore/libGAL.so vivante-gal /usr/lib/galcore/wayland/libGAL.so 30 \
		--slave /usr/lib/galcore/libEGL.so.1 vivante-egl /usr/lib/galcore/wayland/libEGL.so.1 \
		--slave /usr/lib/galcore/libGL.so.1 vivante-gl /usr/lib/galcore/wayland/libGL.so.1 \
		--slave /usr/lib/galcore/libGLESv2.so.2 vivante-gles2 /usr/lib/galcore/wayland/libGLESv2.so.2 \
		--slave /usr/lib/galcore/libVDK.so.1 vivante-vdk /usr/lib/galcore/wayland/libVDK.so.1 \
		--slave /usr/lib/galcore/libvulkan.so.1 vivante-vk /usr/lib/galcore/wayland/libvulkan.so.1
fi

#DEBHELPER#

exit 0
