#!/bin/sh

# handle alternatives
if [ "x$1" = "xconfigure" ]; then
	update-alternatives --install /usr/lib/imx-gpu-viv vivante /usr/lib/imx-gpu-viv-dfb 10
fi

# force-reinstall/repair symlinks
ln -sfv libEGL.so.1 /usr/lib/galcore/libEGL.so
ln -sfv libEGL.so.1.0 /usr/lib/galcore/libEGL.so.1
ln -sfv libEGL.so.1.0 /usr/lib/galcore/libEGL.so.1.0.0
ln -sfv libGLESv2.so.2 /usr/lib/galcore/libGLESv2.so
ln -sfv libGLESv2.so.2 /usr/lib/galcore/libGLESv2.so.2.0.0

#DEBHELPER#

exit 0
